// Preview durch <Strg><Shift>v

= Entwickler/innen/handmagazin
Gruppe 7 <phdi1011@h-ka.de>
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: coderay
:icons: font
// :kroki-server-url: https://kroki.io

// https://github.com/asciidoctor/asciidoctorj
// https://github.com/asciidoctor/asciidoctor-diagram
// http://de.plantuml.com/classes.html
// http://de.plantuml.com/component.html
// https://github.com/odrotbohm/asciidoctor-plantuml

IMPORTANT: Copyright (C) 2023 - present Gruppe 7, Hochschule Karlsruhe. +
           Free use of this software is granted under the terms of the
           GNU General Public License (GPL) v3. +
           For the full text of the license, see the http://www.gnu.org/licenses/gpl-3.0.html[license] file.

== Der Applikationsserver

=== Der Applikationsserver im Überblick

Der Applikationsserver stellt Webseiten oder allgemeine Dateien und Dokumente in einem 
bestimmten Umfeld bereit

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.plantuml[]
----

Übersicht der Use Cases 

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.plantuml[]
----

=== Die REST-Schnittstelle

Representational State Transfer ist ein Paradigma für die Softwarearchitektur von verteilten Systemen, insbesondere für Webservices. REST ist eine Abstraktion der Struktur und des Verhaltens 
des World Wide Web.

."PatientGetController" für Lesezugriffe an der REST-Schnittstelle
[plantuml,PatientGetController,svg]
----
include::PatientGetController.plantuml[]
----

Model View Controllerist ein Muster zur Unterteilung einer Software in die drei Komponenten Datenmodell, Präsentation und Programmsteuerung. Das Muster kann sowohl als Architekturmuster als auch als Entwurfsmuster eingesetzt werden.Ziel des Musters ist ein flexibler Programmentwurf, der eine spätere Änderung oder Erweiterung erleichtert und eine Wiederverwendbarkeit der einzelnen Komponenten ermöglicht. 

."PatientWriteController" für Schreibzugriffe an der REST-Schnittstelle
[plantuml,PatientGetController,svg]
----
include::PatientWriteController.plantuml[]
----

=== Die GraphQL-Schnittstelle

GraphQL ist eine Datenabfragesprache, die vor allem für mobile Nutzer und deren Anforderungen entwickelt wurde und die API-Funktionsweise verbessern soll.

.PatientQueryResolver für Lesezugriffe an der GraphQL-Schnittstelle
[plantuml,PatientQueryResolver,svg]
----
include::PatientQueryResolver.plantuml[]
----

GraphQL ist eine Abfragesprache für Ihre API und eine serverseitige Laufzeit zum Ausführen von Abfragen unter Verwendung eines Typsystems, das Sie für Ihre Daten definieren.

.PatientMutationResolver für Schreibzugriffe an der GraphQL-Schnittstelle
[plantuml,PatientMutationResolver,svg]
----
include::PatientMutationResolver.plantuml[]
----

=== Der Anwendungskern

Geschäftslogik ist im Anwendungskern

."PatientReadService" im Anwendungskern
[plantuml,PatientReadService,svg]
----
include::PatientReadService.plantuml[]
----

Im ReadService werden die Logik vom auslesen der Daten geschrieben und im Write zum 
schreiben der Daten
."PatientWriteService" im Anwendungskern
[plantuml,PatientWriteService,svg]
----
include::PatientWriteService.plantuml[]
----

=== Klasse für Entities

In der Informatik ist eine Entität ein eindeutig identifizierbares, einzelnes Informationsobjekt. Entitäten können sowohl reale Dinge oder Personen als auch abstrakte Objekte sein

.Entity
[plantuml,Patient,svg]
----
include::Patient.plantuml[]
----

== Programmierrichtlinien für TypeScript und JavaScript

Für die Programmierung mit *TypeScript* und *JavaScript* wird folgende
Styleguides empfehlenswert:

[horizontal]
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_Google_:: https://google.github.io/styleguide/tsguide.html
_React_:: https://github.com/airbnb/javascript/tree/master/react
