' Preview durch <Alt>d

@startuml Use Cases

actor Rezeptionist
actor Arzt
actor Patient

rectangle patient {
    Patient --> (Patient suchen)
    Arzt --> (Patient suchen)
    Arzt --> (Patient anlegen)
    Arzt --> (Patient ändern)
    Rezeptionist --> (Patient suchen)
    Rezeptionist --> (Patient anlegen)
    Rezeptionist --> (Patient ändern)
}

footer (c) Gruppe 7

@enduml
